### ISSUE TITLE
private IP lookup for mesh broken

### ISSUE THREAD

**Issue by mikepii** [aerospike/aws-cloudformation#15]
@rguo-aerospike this change breaks clustering for me:

https://github.com/aerospike/aws-cloudformation/commit/37a359a4ca2c4cfbfecaba1edca1ccdb7dae1d67#diff-9784b39c6fd5fe5948b70354c1926ac1R199

`print $3` gives you a DNS name to the private IP, and `print $4` gives you the private IP address itself. Aerospike complains when you give it the DNS name, it needs the IP address. It says the DNS name is not a valid IP address.

**Comment by whyrg** [comment]
As it turns out, the vpc I tested for 3.7.3 doesn't have the DNS HOSTNAMES param on, which removed the hostname from the metadata description, making it the 3rd param.

A future revision would account for the VPC param DNS HOSTNAMES. 
Commit 623475338c3357945c1a46aceb68e6a7075e3d03 has the $3 reverted to $4.

**Comment by mikepii** [comment]
Thanks for checking this out so quickly!
